### ISSUE TITLE
Autocompletion is not working

### ISSUE THREAD

**Issue by eyadsibai** [NFLabs/zeppelin#248]
Autocompletion is not working .... actually not sure if it should?

**Comment by tribbloid** [comment]
after some debugging I'm very sure the backend is perfectly fine.
Ajax Cloud9 Editor caused all problem: snippet/simple completers are not disabled. When there is only 1 snippet option the editor will flush it out, instead of waiting for backend to respond.
BTW ACE is a bit outdated by 0.0.2, maybe upgrade can solve the problem?

**Comment by Leemoonsoo** [comment]
Thanks for valuable informations. I think it's worth to try upgrade ACE editor version.
Very appreciate your help!

**Comment by eyadsibai** [comment]
well... you have a great product here ... wish you the best!

**Comment by swkimme** [comment]
Close this issue since we resolved it by #279
Great job, guys!

**Comment by xhudik** [comment]
probably strange question but  why auto-completion feature is invoked by `ctrl-.` Usually (IdeaJ, Eclipse and some other tools) are using `ctrl-space`. Why is it different in Zeppelin?
