### ISSUE TITLE
Is Mesos supported?

### ISSUE THREAD

**Issue by amiorin** [NFLabs/zeppelin#358]
I'm evaluating zeppelin, but it has to work with our Spark deployment on Mesos.
I don't see Mesos mentioned anywhere. That makes me think that it's not supported at the moment.
Do you need help with mesos integration? I'm available.

**Comment by swkimme** [comment]
Hi Alberto,
Sadly Zeppelin is not tested on Mesos, but you can find some threads
discussing Zeppelin on Yarn. You may get some hint on it.
https://github.com/NFLabs/zeppelin/pull/352

Since Zeppelin community has lack of experience on Mesos,
it will be a great contribution if you can make Zeppelin works on Mesos!!

**Comment by jongyoul** [comment]
@amiorin I've already tested zeppelin under mesos cluster. you can only add `SPARK_HOME` or `JAVA_OPTS="-Dspark.executor.uri=/path/to/spark.tgz"` @swkimme I think we should add an example page or section for running zeppelin on various environments.

**Comment by swkimme** [comment]
@jongyoul 
+1 for adding some docs for various environments, especially YARN or Mesos.
What if we add some additional docs under https://github.com/NFLabs/zeppelin#run first?

**Comment by jongyoul** [comment]
@swkimme Ok, I'll try to add a new section about external cluster configuration under the `Configuration` section

**Comment by jongyoul** [comment]
@swkimme Please close this issue also. :-)

**Comment by swkimme** [comment]
@jongyoul great!
