### ISSUE TITLE
Build failure Ubuntu 14.04

### ISSUE THREAD

**Issue by tdhd** [NFLabs/zeppelin#373]
Hi everyone,

i have problems compiling the master branch (commit 7b7adf6ec43f2043e58be3f35e7ba1375623689e) on ubuntu 14.04 LTS. I have all dependencies installed. The build fails because of a missing file '_tools/checkstyle.xml' which is weird because the file exists.

See https://gist.github.com/tdhd/13d762fc1e23e18fb255 for the build log.

Best regards

**Comment by Denspa** [comment]
try mvn install -DskipTests

**Comment by tdhd** [comment]
Unfortunately the same error, i attached the build log with -e switch enabled this time (https://gist.github.com/tdhd/4d30b38fe938d6cbe49f)

**Comment by jongyoul** [comment]
@tdhd This error occurs when you use maven 2.2.1 which cannot find the location of checkstyle.xml. This will be reserved by a few effort. But, after you resolve this issue, you cannot build Zeppelin still because frontend-maven-plugin which should use maven 3.1+. Can you change your maven version up to 3.1? And @Leemoonsoo What do you think of supporting maven 2.2.1?

**Comment by swkimme** [comment]
@jongyoul 
It will be good if we can support maven 2.X. Do you know how to support frontend-maven-plugin build in maven 2.X?

**Comment by jongyoul** [comment]
@swkimme I don't find it yet because I think it's not easy. That plugin depends on http://mvnrepository.com/artifact/com.github.eirslett/frontend-maven-plugin/0.0.20.

**Comment by tdhd** [comment]
It also compiles with maven 3.0.5, I just tried it. Awesome project!

**Comment by jongyoul** [comment]
@tdhd Good!

**Comment by jongyoul** [comment]
@tdhd Could you please close this issue if you resolve a problem?
