### ISSUE TITLE
Some issues about using zeppelin.

### ISSUE THREAD

**Issue by Anne623** [NFLabs/zeppelin#409]
Hi, I use Zeppelin yesterday firstly, I find some operation is not working.

1. When I Create New note,I click the button ```Create new note```, I think it will be open the notebook which i created just now , while nothing happened, only add a new note in menu(note list). while the note list is order by ```string```, and I didn't rename my oldest notebook, so I can not sure which notebook is new i just create.

2.  I go into one notebook, there are many buttons in notebook window, I want to know each button's function，so I think it will be some tooltips when my cursor is positioned over the button, while nothing happened , so I only click one by one to check each button's function.

I first use zeppelin, did I miss some config for upon operation?

Thank you, :)

**Comment by corneadoug** [comment]
Hi,

As the README.md of the project is stating, the project moved to Apache Foundation.
We are no longer using this Github to get new issues (we use our ASF JIRA)

Now to answer you quickly:

You didn't miss anything in your configuration, Zeppelin is working like that.
Some issues were already opened for both your points:

1) This issue was discussed in the mailing list, but I guess no issue was created,
If you want to create an issue you can go on the JIRA: https://issues.apache.org/jira/browse/zeppelin/
Check existing issue before creating one

2) Exist here: https://issues.apache.org/jira/browse/ZEPPELIN-35
